version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-inclue-email)
      - REPO=$(aws ecr describe-repositories --repository-names terraform-codepipeline-ecs-test --output text --query "repositories[0].repositoryUri")
      - IMAGE=$REPO:latest
  build:
    commands:
      - docker build -t $IMAGE ./app
      - docker push $IMAGE
  post_build:
    commands:
      - printf '[{"name":"","imageUri":"%s"}]' $IMAGE > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
